### ISSUE TITLE
Fixed length?

### ISSUE THREAD

**Issue by preke** [lsrock1/abcnn_pytorch#1]
I was focus on the params of your implementation. And I found that there is a parameter 'strlenmax' which you set it with 15.
Is that means in your model, you kind of actually pad each sentence to 15 words?

**Comment by lsrock1** [comment]
strlenmax means that sentences will be padded or cut to have same size

In ABCNN papers, they said 'we pad the two sentences to have the same length. However, in the figures we show different lengths because this gives a better intuition of how the model works.'
So, figures in paper seem to have different length but actually they have same length.
strlenmax should be decided appropriately. It affects the accuracy 1~3 points in my experiment

That is why strlenmax exists. same size makes model work.
Maybe my sentences are not clear, please comment.

**Comment by preke** [comment]
Oh, I see. Thanks for your answer.

**Comment by preke** [comment]
I think if you use _torchtext_ to load your data, it would help you automatically pad each batch of sentences to the same length.

**Comment by lsrock1** [comment]
@preke Thanks, i didn't know torchtext!
